### PR TITLE
Fix empty base Option move assignment

### LINKED ISSUE #3: Empty base `Option` move assignment operator does not work
https://github.com/ampron/functional/blob/a174489ead1094e61221a3f01bc8e47e88c09e4b/functional/include/fun/option/option_inner.h#L33

`if (_variant)` should be `if (_variant == Tag::SOME)` and should probably just do `T::operator=(other)`, since the assignment is done purely for potential side-effects.

### PR DESCRIPTION
**Pull request by jjcamp**
Fixes #3

### CODE REVIEW

File: test/all_tests.cpp [hunk 1]
```diff
@@ -546,6 +546,22 @@ TEST(OptionTest, destruct_after_take) {
...
+  auto op1 = fun::some(Empty());
+  EXPECT_TRUE(op1.is_some());
+  fun::Option<Empty> op2 {};
+  EXPECT_TRUE(op2.is_none());
+  op2 = std::move(op1);
+  EXPECT_TRUE(op2.is_some());
+  EXPECT_TRUE(op1.is_none());
+  op1.emplace(Empty());
+  EXPECT_TRUE(op1 == op2);
+}
```
Comment (ampron) [inline test/all_tests.cpp]: Please use `fun::Unit` instead of `Empty`. The following copy should be an easy copy-and-paste fix.

```
TEST(OptionTest, empty_base) {
  auto op1 = fun::some(fun::Unit());
  EXPECT_TRUE(op1.is_some());
  fun::Option<fun::Unit> op2 {};
  EXPECT_TRUE(op2.is_none());
  op2 = std::move(op1);
  EXPECT_TRUE(op2.is_some());
  EXPECT_TRUE(op1.is_none());
  op1.emplace(fun::Unit());
  EXPECT_TRUE(op1 == op2);
}
```
